[package]
name = "dynamodb-scanx-core"
version = "0.1.0"
edition = "2021"
authors = ["Luis Parada <pradapop78@gmail.com>"]
description = "Core engine for DynamoDB parallel scanning and STS AssumeRole."
license = "MIT"
repository = "https://github.com/Luenpa01/dynamodb-scanx-rs"

[dependencies]
tokio = { version = "1", features = ["full"] }

aws-config = "1.1"
aws-sdk-sts = "1.1"
aws-sdk-dynamodb = "1.1"
aws-credential-types = "1.1"
